spring:
  application:
    name: identity-service
  profiles:
    active: development

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.sm.identity: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO 