spring:
   cloud:
      gateway:
         routes:
         - id: User-Service
           uri: lb://User-Service
           predicates:
           - Path= /user/**
         - id: Post-Service
           uri: lb://Post-Service
           predicates:
           - Path= /user_post/**