spring:
   redis:
      host: localhost
      port: 6379
   cloud:
      gateway: 
         default-filters: 
          - name: CorrelationFilter
         routes:
         - id: User-Service
           uri: lb://User-Service
           predicates:
             - Path= /user/**
           filters: 
           - name: AuthenticationFilter 
           - name: RequestRateLimiter
             args: 
               key-resolver: '#{@keyResolver}'
               redis-rate-limiter.replenishRate: 20
               redis-rate-limiter.burstCapacity: 40
                 
                 
         - id: Post-Service
           uri: lb://Post-Service
           predicates:
           - Path= /user_post/**
           filters:
           - name:  AuthenticationFilter
           - name: RequestRateLimiter
             args: 
               key-resolver: '#{@keyResolver}'
               redis-rate-limiter.replenishRate: 10
               redis-rate-limiter.burstCapacity: 20
           
         - id: Identity-Service
           uri: lb://Identity-Service
           predicates:
           - Path= /auth/**
           filters:
           - name: RequestRateLimiter
             args: 
               key-resolver: '#{@keyResolver}'
               redis-rate-limiter.replenishRate: 10
               redis-rate-limiter.burstCapacity: 20